$!
$!  RUN.COM - run CC test
$!
$ SET NOCONTROL=Y
$ SET PROCESS/PRIO=2
$ PROC_FILE = F$ENVIRONMENT("PROCEDURE")
$ CREATE/DIRECTORY/NOLOG [.TEMP.'P1']
$ SET DEFAULT [.TEMP.'P1']
$LOOP:
$ COPY [-.-]HW.C []*.*
$ CC/LIST HW.C + SYS$LIBRARY:SYS$STARLET_C.TLB/LIBRARY
$ PURGE/NOLOG
$ LINK/MAP HW.OBJ
$ PURGE/NOLOG
$ DEFINE/USER SYS$OUTPUT NLA0:
$ RUN HW.EXE
$ GOTO LOOP