$ IF P1 .EQS. "DEBUG"
$ THEN
$     CC := CC /DEBUG=ALL/NOOPTIMIZE/LIST/MACHINE_CODE
$     LINK := LINK/DEBUG
$ ELSE
$     CC := CC /NODEBUG/OPTIMIZE/LIST/MACHINE_CODE
$     LINK := LINK/NOTRACE
$ ENDIF
$ CC PAGE.C + SYS$LIBRARY:SYS$STARLET_C.TLB/LIBRARY
$ LINK PAGE.OBJ
$ PAGE :== $SYS$DISK:[]PAGE