$!
$!  RUN.COM - run CPU_HOG image
$!
$ SET NOCONTROL=Y
$ SET PROCESS/PRIO=1
$ PROC_FILE = F$ENVIRONMENT("PROCEDURE")
$ RUN_FILE = F$PARSE(PROC_FILE,,,"DEVICE","SYNTAX_ONLY") + -
             F$PARSE(PROC_FILE,,,"DIRECTORY","SYNTAX_ONLY") + -
             "CPU_HOG.EXE"
$ RUN 'RUN_FILE'