$ IF P1 .EQS. "DEBUG"
$ THEN
$     CC := CC /DEBUG=ALL/NOOPTIMIZE/LIST/MACHINE_CODE
$     LINK := LINK/DEBUG
$ ELSE
$     CC := CC /NODEBUG/OPTIMIZE/LIST/MACHINE_CODE
$     LINK := LINK/NOTRACE
$ ENDIF
$ CC FILE.C + SYS$LIBRARY:SYS$STARLET_C.TLB/LIBRARY
$ LINK FILE.OBJ
$ FILE :== $SYS$DISK:[]FILE