$!
$!  RUN.COM - run FILE test
$!
$ SET NOCONTROL=Y
$ SET PROCESS/PRIO=3
$ IF F$SEARCH("TEMP.DIR") .EQS. "" THEN CREATE/DIRECTORY/NOLOG [.TEMP]
$ SET DEFAULT [.TEMP]
$ FILE := $SYS$DISK:[-]FILE.EXE
$LOOP:
$ FILE 'P1' 'P2' 'P3'
$ GOTO LOOP